import Head from 'next/head';
import { PostCard } from '@components/index';
import { withAuthRoute } from '@hoc/withAuthRoute';

const HomePage = () => {
  return (
    <>
      <Head>
        <title>Home - Twitter</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <PostCard />
    </>
  );
};

export default withAuthRoute(HomePage);
