import Head from 'next/head';
import { ComposeCard, PostCard } from '@components/index';
import { withAuthRoute } from '@hoc/withAuthRoute';
import { useQuery } from 'react-query';
import { getTweets } from '@utils/api';
import { useSelector } from 'react-redux';

const HomePage = () => {
  const {
    user: { token },
  } = useSelector(state => state.auth);
  const { data: tweets, isLoading } = useQuery('tweets', () =>
    getTweets(token)
  );

  if (isLoading) return 'Loading...';
  return (
    <>
      <Head>
        <title>Home - Twitter</title>
        {/* <meta name='description' content='Generated by create next app' /> */}
      </Head>
      <ComposeCard />
      <div className='border border-gray-200 divide-y divide-gray-200 mt-5'>
        {tweets.map(tweet => (
          <PostCard key={tweet._id} {...{ tweet }} />
        ))}
      </div>
    </>
  );
};

export default withAuthRoute(HomePage);
