import Head from 'next/head';
import { PostCard } from '@components/index';
import { withAuthRoute } from '@hoc/withAuthRoute';

const HomePage = () => {
  return (
    <div className='max-w-4xl w-full mx-auto container pb-16'>
      <Head>
        <title>Home - Twitter</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <PostCard />
    </div>
  );
};

export default withAuthRoute(HomePage);
